networks: 
  vote: 
    driver: bridge
  front-tier:
  back-tier:    

volumes: 
  db-data: 

services: 
    redis: 
      image: redis:alpine
      networks: 
        - vote
    
    vote:
      build:
        context: ./vote
        dockerfile: Dockerfile
      ports:
        - "80:80"
      networks:
        - vote
        - front-tier
        - back-tier
      depends_on:
        - redis
        - db        

    
    worker:
      image: initcron/worker:v2
      networks:
        - vote
      depends_on:
      - redis
      deploy:
        resources:
          limits:
            memory: 512M
          reservations:
            memory: 256M
      mem_limit: 256m  
 
    worker_for_maven:
      build:
        context: ./worker
        dockerfile: Dockerfile
      networks:
        - vote
      depends_on:
        - redis
        - db
      mem_limit: 256m

    db:
      image: postgres:9.4
      environment:
        POSTGRES_PASSWORD: postgres
      networks:
        - vote
        - back-tier

      volumes:
        - "db-data:/var/lib/postgresql/data"
   
    results: 
      image: schoolofdevops/vote-result
      ports:
        - 5001:80
      depends_on: 
        - db
      networks: 
        - vote
    
    adminer:
      image: adminer
      ports:
        - "8080:8080"
      networks:
        - vote

    dotnet-worker:
      build:
        context: ./worker_dotnet
        dockerfile: Dockerfile
      networks:
        - vote
        - back-tier
      depends_on:
        - redis
        - db

    sut:
      build:
        context: ./e2e/tests/
      depends_on:
        - vote
        - result
        - worker
      networks:
        - front-tier

    result:
      build:
        context: ./result
        dockerfile: Dockerfile
      ports:
        - "5002:80"
      depends_on:
        - redis
        - db
      networks:
        - front-tier
        - back-tier

